--liquibase formatted sql

--changeSet kalea.wolff:add-payee-table-and-sequence
CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."PAYEE_ID_SEQ" START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 10;

CREATE CACHED TABLE "PUBLIC"."PAYEE"(
    "PAYEE_ID" BIGINT NOT NULL,
    "COMPANY_NAME" VARCHAR(255) NOT NULL,
    "POSTAL_CODE" VARCHAR(20) NULL,
    "ACCOUNT_NUMBER" VARCHAR(255) NOT NULL,
    "NICKNAME" VARCHAR(60) NULL,
    "CUSTOMER_ID" BIGINT NOT NULL
);

ALTER TABLE "PUBLIC"."PAYEE" ADD CONSTRAINT "PUBLIC"."PK_PAYEE_ID" PRIMARY KEY("PAYEE_ID");
ALTER TABLE "PUBLIC"."PAYEE" ADD CONSTRAINT "PUBLIC"."FK_PAYEE_CUSTOMER_ID" FOREIGN KEY("CUSTOMER_ID")
    REFERENCES "PUBLIC"."CUSTOMER"("USR_ID") NOCHECK;

--changeSet kalea.wolff:add-payee-id-to-transaction
ALTER TABLE "PUBLIC"."TRANSACTION" ADD "PAYEE_ID" BIGINT;

--changeSet taka.watanabe:add-active-flag-to-payee
ALTER TABLE "PUBLIC"."PAYEE" ADD "ACTIVE_FL" NUMBER(1);

--changeSet kalea.wolff:add-fields-to-checking-table
ALTER TABLE "PUBLIC"."CHECKING" ADD "MONTHLY_TRANS_AMOUNT" NUMBER(2);
ALTER TABLE "PUBLIC"."CHECKING" ADD "MON_TRANS_REMAINING" NUMBER(2);
ALTER TABLE "PUBLIC"."CHECKING" ADD "MONTHLY_SRVC_FEE_FL" NUMBER(1);

--changeSet kalea.wolff:modify-customer-and-accounts
ALTER TABLE "PUBLIC"."CUSTOMER" DROP COLUMN "MAIN_ACCT_ID";
ALTER TABLE "PUBLIC"."ACCOUNT" DROP COLUMN "OPENED_BY_CUST_ID";
ALTER TABLE "PUBLIC"."ACCOUNT" DROP COLUMN "AUTH_CUST_ID";
ALTER TABLE "PUBLIC"."ACCOUNT" ADD "MAIN_ACCOUNT_FL" NUMBER(1);

--changeSet kalea.wolff:modify-checking-remove-not-null-transaction-fee
ALTER TABLE "PUBLIC"."CHECKING" ALTER COLUMN "TRANSACTION_FEE" SET NULL;

--changeSet kalea.wolff:add-main-acct-id-back-to-customer
ALTER TABLE "PUBLIC"."CUSTOMER" ADD "MAIN_ACCT_ID" BIGINT;
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."FK_CUSTOMER_MAIN_ACCT" FOREIGN KEY("MAIN_ACCT_ID")
    REFERENCES "PUBLIC"."ACCOUNT"("ACC_ID") NOCHECK;

--changeSet kalea.wolff:add-transaction-memo-column
ALTER TABLE "PUBLIC"."TRANSACTION" ADD "TRANSACTION_MEMO" VARCHAR(35);

--changeset kalea.wolff:fix-typo-in-savings-column
ALTER TABLE "PUBLIC"."SAVINGS" ALTER COLUMN "MNIN_BALANCE_CHARGE" RENAME TO "MIN_BALANCE_CHARGE";

--changeSet taka.watanabe:add-student-table
CREATE CACHED TABLE "PUBLIC"."STUDENT"(
    "ACC_ID" BIGINT NOT NULL,
    "ELIGIBILITY_FL" NUMBER(1) NOT NULL,
    "MONTHLY_SRVC_FEE" DECIMAL(19, 2) NOT NULL
);

ALTER TABLE "PUBLIC"."STUDENT" ADD CONSTRAINT "PUBLIC"."FK_STUDENT_ACCID_ACCT_ACCID" FOREIGN KEY("ACC_ID")
    REFERENCES "PUBLIC"."ACCOUNT"("ACC_ID") NOCHECK;

--changeset taka.wataname:update-datatype-of-interest-rate-column
ALTER TABLE "PUBLIC"."SAVINGS" ALTER COLUMN "INTEREST_RATE" SET DATA TYPE DECIMAL(19,5);

--changeSet taka.wataname:add-fields-to-checking-table
ALTER TABLE "PUBLIC"."CHECKING" ADD "MONTHLY_SRVC_FEE" DECIMAL(19, 2);
ALTER TABLE "PUBLIC"."CHECKING" ADD "MONTHLY_MIN_BAL" DECIMAL(19, 2);
ALTER TABLE "PUBLIC"."CHECKING" ADD "E_TRANSFER_FEE" DECIMAL(19, 2);

--changeSet taka.watanabe:add-first-class-checking-table
CREATE CACHED TABLE "PUBLIC"."FIRST_CLASS_CHECKING"(
    "ACC_ID" BIGINT NOT NULL,
    "MONTHLY_SRVC_FEE_FL" NUMBER(1) NOT NULL,
    "MONTHLY_SRVC_FEE" DECIMAL(19, 2) NOT NULL,
    "MONTHLY_MIN_BAL" DECIMAL(19, 2) NOT NULL
);

ALTER TABLE "PUBLIC"."FIRST_CLASS_CHECKING" ADD CONSTRAINT "PUBLIC"."FK_FC_CKG_ACCID_ACCT_ACCID" FOREIGN KEY("ACC_ID")
    REFERENCES "PUBLIC"."ACCOUNT"("ACC_ID") NOCHECK;

--changeSet taka.watanabe:add-business-visa-table
CREATE CACHED TABLE "PUBLIC"."BUSINESS_VISA"(
    "ACC_ID" BIGINT NOT NULL,
    "CASH_BACK_RATE" DECIMAL(19, 5) NOT NULL,
    "CASH_BACK_AMOUNT" DECIMAL(19, 2) NOT NULL,
    "INTEREST_RATE" DECIMAL(19, 5) NOT NULL,
    "MON_CHARGED_INTEREST" DECIMAL(19, 2) NOT NULL,
    "CREDIT_LIMIT" DECIMAL(19, 2) NOT NULL,
    "LIMIT_INCREASE_REQ_DT" TIMESTAMP,
    "ANNUAL_FEE" DECIMAL(19, 2) NOT NULL
);

ALTER TABLE "PUBLIC"."BUSINESS_VISA" ADD CONSTRAINT "PUBLIC"."FK_BUS_VISA_ACCID_ACCT_ACCID" FOREIGN KEY("ACC_ID")
    REFERENCES "PUBLIC"."ACCOUNT"("ACC_ID") NOCHECK;

--changeSet taka.watanabe:add-premium-visa-table
CREATE CACHED TABLE "PUBLIC"."PREMIUM_VISA"(
    "ACC_ID" BIGINT NOT NULL,
    "CASH_BACK_RATE" DECIMAL(19, 5) NOT NULL,
    "CASH_BACK_AMOUNT" DECIMAL(19, 2) NOT NULL,
    "INTEREST_RATE" DECIMAL(19, 5) NOT NULL,
    "MON_CHARGED_INTEREST" DECIMAL(19, 2) NOT NULL,
    "CREDIT_LIMIT" DECIMAL(19, 2) NOT NULL,
    "LIMIT_INCREASE_REQ_DT" TIMESTAMP
);

ALTER TABLE "PUBLIC"."PREMIUM_VISA" ADD CONSTRAINT "PUBLIC"."FK_PREVISA_ACCID_ACCT_ACCID" FOREIGN KEY("ACC_ID")
    REFERENCES "PUBLIC"."ACCOUNT"("ACC_ID") NOCHECK;

--changeSet kalea.wolff:add-password-expiration-fields
ALTER TABLE "PUBLIC"."USR_TABLE" ADD "PASSWORD_EXPIRES_DT" TIMESTAMP;

--changeSet kalea.wolff:add-account-lockout-fields
ALTER TABLE "PUBLIC"."USR_TABLE" ADD "ACCOUNT_LOCKED_FL" NUMBER(1) DEFAULT 0;
ALTER TABLE "PUBLIC"."USR_TABLE" ADD "FAILED_LOGIN_COUNT" NUMBER(1) DEFAULT 0;
ALTER TABLE "PUBLIC"."USR_TABLE" ADD "LAST_FAILED_LOGIN_DT" TIMESTAMP;

--changeSet kalea.wolff:add-account-expired-fields
ALTER TABLE "PUBLIC"."USR_TABLE" ADD "ACCOUNT_EXPIRES_DT" TIMESTAMP;
