--liquibase formatted sql

--changeSet kalea.wolff:change-pk-fields-to-use-bigint-not-decimal
ALTER TABLE "PUBLIC"."USR_TABLE" ALTER COLUMN "USR_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."USR_TABLE" ALTER COLUMN "FK_ADDRESS_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."TRANSACTION" ALTER COLUMN "TRANSACTION_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."SAVINGS" ALTER COLUMN "ACC_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."CUSTOMER" ALTER COLUMN "USR_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."CHECKING" ALTER COLUMN "ACC_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."ADMIN_TABLE" ALTER COLUMN "USR_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."ADDRESS" ALTER COLUMN "ADDRESS_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."ACCOUNT" ALTER COLUMN "ACC_ID" SET DATA TYPE BIGINT;
ALTER TABLE "PUBLIC"."ACCOUNT" ALTER COLUMN "FK_CUSTOMER_ID" SET DATA TYPE BIGINT;

--changeSet kalea.wolff:alter-address-suite-number-allow-null
ALTER TABLE "PUBLIC"."ADDRESS" ALTER COLUMN "SUITE_NUMBER" SET NULL;

--changeSet kalea.wolff:add-role-column-to-user
ALTER TABLE "PUBLIC"."USR_TABLE" ADD "ROLE" VARCHAR(20);

--changeSet kalea.wolff:add-is-active-flag-to-user
ALTER TABLE "PUBLIC"."USR_TABLE" ADD "ACCOUNT_ACTIVE_FL" BOOLEAN DEFAULT TRUE;

--changeSet neha.pal:modify-account-structure
CREATE TABLE "PUBLIC"."CUSTOMER_ACCOUNTS" (
    CUSTOMER_ID BIGINT NOT NULL,
    ACC_ID BIGINT NOT NULL
);
