--liquibase formatted sql

--changeSet kalea.wolff:create-initial-user-and-sequences
CREATE USER IF NOT EXISTS "SA" SALT '9998497dfe88a5d6' HASH '2204abea0324e27d61359466964c621428aa115e7be272241142bd799f07791a' ADMIN;

CREATE SEQUENCE "PUBLIC"."USER_PK_SEQ" START WITH 1;
CREATE SEQUENCE "PUBLIC"."TRANSACTION_PK_SEQ" START WITH 1;
CREATE SEQUENCE "PUBLIC"."ADDRESS_PK_SEQ" START WITH 1;
CREATE SEQUENCE "PUBLIC"."ACCOUNT_PK_SEQ" START WITH 1;

--changeSet kalea.wolff:create-initial-tables
CREATE CACHED TABLE "PUBLIC"."USR_TABLE"(
    "USR_ID" DECIMAL(19, 2) NOT NULL,
    "OCCUPATION" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "FIRST_NAME" VARCHAR(255),
    "INDUSTRY" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    "USER_PASSWORD" VARCHAR(255),
    "PHONE_NUMBER" VARCHAR(255),
    "SIN" VARCHAR(255),
    "TITLE" VARCHAR(255),
    "USER_NAME" VARCHAR(255),
    "FK_ADDRESS_ID" DECIMAL(19, 2)
);
CREATE CACHED TABLE "PUBLIC"."TRANSACTION"(
    "TRANSACTION_ID" INTEGER NOT NULL,
    "AMOUNT" DOUBLE NOT NULL,
    "DATE_TIME" TIMESTAMP,
    "TRANSACTION_TYPE" VARCHAR(255),
    "FK_ACCOUNT_ID" DECIMAL(19, 2)
);
CREATE CACHED TABLE "PUBLIC"."SAVINGS"(
    "INTEREST_RATE" DECIMAL(19, 2) NOT NULL,
    "MIN_BALANCE" DECIMAL(19, 2) NOT NULL,
    "MNIN_BALANCE_CHARGE" DECIMAL(19, 2),
    "ACC_ID" DECIMAL(19, 2) NOT NULL
);
CREATE CACHED TABLE "PUBLIC"."CUSTOMER"(
    "INCOME" DECIMAL(19, 2),
    "USR_ID" DECIMAL(19, 2) NOT NULL
);
CREATE CACHED TABLE "PUBLIC"."CHECKING"(
    "TRANSACTION_FEE" DECIMAL(19, 2) NOT NULL,
    "ACC_ID" DECIMAL(19, 2) NOT NULL
);
CREATE CACHED TABLE "PUBLIC"."ADMIN_TABLE"(
    "USR_ID" DECIMAL(19, 2) NOT NULL
);
CREATE CACHED TABLE "PUBLIC"."ADDRESS"(
    "ADDRESS_ID" DECIMAL(19, 2) NOT NULL,
    "CITY" VARCHAR(255) NOT NULL,
    "POSTAL_CODE" VARCHAR(255) NOT NULL,
    "PROVINCE" VARCHAR(255) NOT NULL,
    "STREET_NAME" VARCHAR(255) NOT NULL,
    "STREET_NUMBER" VARCHAR(255) NOT NULL,
    "SUITE_NUMBER" VARCHAR(255) NOT NULL
);
CREATE CACHED TABLE "PUBLIC"."ACCOUNT"(
    "ACC_ID" DECIMAL(19, 2) NOT NULL,
    "ACCOUNT_TYPE" VARCHAR(255),
    "ACCOUNT_BALANCE" DECIMAL(19, 2),
    "FK_CUSTOMER_ID" DECIMAL(19, 2)
);

--changeSet kalea.wolff:add-constraints-to-tables
ALTER TABLE "PUBLIC"."USR_TABLE" ADD CONSTRAINT "PUBLIC"."UK_MGHF2VE0S2VOW6A2KCN31097W" UNIQUE("USER_NAME");
ALTER TABLE "PUBLIC"."USR_TABLE" ADD CONSTRAINT "PUBLIC"."UK_LGGBFTBH7XHD0I9MU40XRDRNA" UNIQUE("EMAIL");
ALTER TABLE "PUBLIC"."USR_TABLE" ADD CONSTRAINT "PUBLIC"."UK_L4V3X784L6SYE8AFMPW7B1OS7" UNIQUE("PHONE_NUMBER");
ALTER TABLE "PUBLIC"."USR_TABLE" ADD CONSTRAINT "PUBLIC"."FKHNCHWXDHH4TMMMDTH5205PATP" FOREIGN KEY("FK_ADDRESS_ID") REFERENCES "PUBLIC"."ADDRESS"("ADDRESS_ID") NOCHECK;
ALTER TABLE "PUBLIC"."USR_TABLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_81" PRIMARY KEY("USR_ID");
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."FK7SJUCA1JNJOLTG2DFSE9SAI53" FOREIGN KEY("FK_ACCOUNT_ID") REFERENCES "PUBLIC"."ACCOUNT"("ACC_ID") NOCHECK;
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("TRANSACTION_ID");
ALTER TABLE "PUBLIC"."SAVINGS" ADD CONSTRAINT "PUBLIC"."FKFLT4WWF1OKK4UIO7HKNFRK175" FOREIGN KEY("ACC_ID") REFERENCES "PUBLIC"."ACCOUNT"("ACC_ID") NOCHECK;
ALTER TABLE "PUBLIC"."SAVINGS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ACC_ID");
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."FK8LMUHE0CJCJCHB26X3M35UEIN" FOREIGN KEY("USR_ID") REFERENCES "PUBLIC"."USR_TABLE"("USR_ID") NOCHECK;
ALTER TABLE "PUBLIC"."CUSTOMER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("USR_ID");
ALTER TABLE "PUBLIC"."CHECKING" ADD CONSTRAINT "PUBLIC"."FKQTY8KKLWD61QNUA0YJYX12GL2" FOREIGN KEY("ACC_ID") REFERENCES "PUBLIC"."ACCOUNT"("ACC_ID") NOCHECK;
ALTER TABLE "PUBLIC"."CHECKING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ACC_ID");
ALTER TABLE "PUBLIC"."ADMIN_TABLE" ADD CONSTRAINT "PUBLIC"."FK73C24ECL42O1OGKV6C9VAOTUH" FOREIGN KEY("USR_ID") REFERENCES "PUBLIC"."USR_TABLE"("USR_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ADMIN_TABLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("USR_ID");
ALTER TABLE "PUBLIC"."ADDRESS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E6" PRIMARY KEY("ADDRESS_ID");
ALTER TABLE "PUBLIC"."ACCOUNT" ADD CONSTRAINT "PUBLIC"."FKTDW44GPPRHE5TS5XX35O950XA" FOREIGN KEY("FK_CUSTOMER_ID") REFERENCES "PUBLIC"."CUSTOMER"("USR_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ACC_ID");